apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: meunginx
  name: meunginx2
spec:
  containers:
  - image: nginx
    name: meunginx
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
