apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: meunginx
  name: meunginx
spec:
  containers:
  - image: nginx
    name: meunginx
    ports:
    - containerPort: 80
    resources: {}
  - image: busybox
    name: busybox
    args:
      - sleep
      - "30"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
