apiVersion: v1
kind: Pod
metadata:
  labels:
    run: meunginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: meunginx
    volumeMounts:
    - mountPath: /giropops
      name: primeiro-emptydir
    ports:
    - containerPort: 80
    resources:
      limits: 
        cpu: "0.5"
        memory: "128Mi"
      requests:
        cpu: "0.3"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: primeiro-emptydir
    emptyDir:
      sizeLimit: 256Mi
status: {}
